"""Added user model

Revision ID: 9104e71953b2
Revises: 4c467398448d
Create Date: 2023-12-13 18:49:55.425231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9104e71953b2"
down_revision = "00815cdf52f6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("username"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
